export const GET_USERS = "GET_USERS"
export const GET_USERS_FAILED = "GET_USERS"
export const GET_POSTS = "GET_POSTS"
export const GET_POSTS_FAILED = "GET_POSTS_FAILED"
export const GET_USER_POSTS = "GET_USER_POSTS"
export const GET_CURRENT_USER = "GET_CURRENT_USER"
export const GET_CURRENT_USER_FAILED = "GET_CURRENT_USER_FAILED"
export const GET_POST = "GET_POST"
export const GET_POST_FAILED = "GET_POST_FAILED"
export const GET_COMMENTS = "GET_COMMENTS"
export const GET_COMMENTS_FAILED = "GET_COMMENTS_FAILED"

export const ADD_POST = "ADD_POST"

export const EDIT_POST = "EDIT_POST"

export const DELETE_POST = "DELETE_POST"


export const CLEAR_POST = "CLEAR_POST"
export const CLEAR_COMMENTS = "CLEAR_COMMENTS"
export const CLEAR_CURRENT_USER = "CLEAR_CURRENT_USER"
